spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#      format_sql: true
        show_sql: true
#        dialect: postres
  sql:
    init:
      mode: always

server:
  port: 8083

spring.application.name: user-manage-app-jpa